### ISSUE TITLE
Imperial Support 

### ISSUE THREAD

**Issue by MarkHofmann11** [pilotak/HomeAssistant-CustomComponents#12]
Not an issue, but wondering if there would be a way to add Imperial support (Fahrenheit/inches Hg, etc) for the various sensors?  Just found this today and it is AWESOME!  I run Weather Display and Home Assistant, host my station at www.weather-station.org.  Would be great to have the ability to pull these sensors from clientraw.txt directly into Home Assistant!

**Comment by pilotak** [comment]
I might be able to get some time next week to have a look at it. What it the direct url for `clientraw.txt`?

**Comment by MarkHofmann11** [comment]
That would be fantastic!  Here is a direct link to my clientraw:  http://www.weather-station.org/wdisplay/clientraw.txt

**Comment by pilotak** [comment]
Hi @MarkHofmann11 i have update the code. Could you please test?

**Comment by MarkHofmann11** [comment]
I copied clientraw into .homeassistant/custom_components - is there anything else I need to do in order to see the Weather Display sensors from clientraw?    I don't have anything for this in configuration.yaml - assuming I'm missing some config settings.

**Comment by MarkHofmann11** [comment]
Here is what I am getting in the log:
2019-04-22 16:24:57 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.clientraw.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "d:\homeassistant\lib\site-packages\homeassistant\loader.py", line 117, in _load_file
    module = importlib.import_module(path)
  File "D:\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Home Assistant\AppData\Roaming\.homeassistant\custom_components\clientraw\sensor.py", line 12, in <module>
    from homeassistant.const import (
ImportError: cannot import name 'PRESSURE_HPA' from 'homeassistant.const' (d:\homeassistant\lib\site-packages\homeassistant\const.py)
2019-04-22 16:24:57 ERROR (MainThread) [homeassistant.loader] Unable to find platform clientraw
2019-04-22 16:25:04 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "d:\homeassistant\lib\site-packages\homeassistant\helpers\service.py", line 289, in _handle_service_platform_call

**Comment by pilotak** [comment]
please see config [example](https://github.com/pilotak/HomeAssistant-CustomComponents/blob/master/clientraw/sensor.clientraw.markdown) in this repo in order for this to setup. I have tested this in version `0.91.1` it currently doesn't work in `0.92.0b2`

**Comment by MarkHofmann11** [comment]
Thanks, I have everything setup - but still getting this error (which has to do with imperial support, since my pressure readings would be inHg.

ImportError: cannot import name 'PRESSURE_HPA' from 'homeassistant.const' (d:\homeassistant\lib\site-packages\homeassistant\const.py)

I checked and don't have that constant variable anywhere, which is why I'm getting the error.  It seems all the other ones are good minus pressure.  Going to try and run it with the pressure commented out.

**Comment by pilotak** [comment]
and what version of HA are you running?

**Comment by MarkHofmann11** [comment]
0.87.  I have not upgraded due to the issues with the TP-Link lights with > 0.89.

**Comment by pilotak** [comment]
then as you said you will have comment out the pressure at `#L43` and also `#L235 -> #L242`. Pressure utils were added a month ago to `homeassistant/util/pressure.py` in PR `https://github.com/home-assistant/home-assistant/pull/21210` if it's working otherwise could we consider this as closed?

**Comment by MarkHofmann11** [comment]
I can't confirm it is working yet, as that error prevents any of the elements from working.  You can close the issue if you want and once I upgrade HA to the latest version, will check again.  I'm still waiting for some TP-Link based fixes to be completed before upgrading HA.

**Comment by pilotak** [comment]
Once you get upgraded, feel free to re-open this issue if any problem
